  version 2.1

  jobs:
    build:
      docker:
        -image: circleci/mode:latest
      steps:
        -checkout
        -run:
          name: install dependencies
          command: npm install
        -run:
          name: Grant file permissions
          command: chmod +x ./node_modules/.bin/gh-pages
        -run:
          name: Announce Github User
          command: git config --global user.email "sandy.thomas@calbaptist.edu" && git config --global user.name "sandythomas1"
        -run:
          name: Deploy to GitHub Pages
          command: npx gh-pages -d Wordle-Clone
  workflows:
    version: 2
    deploy:
      jobs:
        -build:
          filters:
            branches:
              only: main
